Repository Team-Sunshijo/Sunshijo-iOS, pull requests merged in 2023-05, with the labels that each got.

#5 ➰:: (#4) PackageLibrary 삭제
  PackageLibrary/Sources/TempFile.swift
Labels: chore

#3 ➰:: (#2) KeychainModule 추가
  Application/Project.swift
  Modules/KeychainModule/Project.swift
  Modules/KeychainModule/Sources/KeychainKeyType.swift
  Modules/KeychainModule/Sources/KeychainModule.swift
  Modules/TestModule/Sources/TempFile.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Modules.swift
Labels: 기능 추가

#7 ➰:: (#6) bundle id 수정
  Application/Project.swift
  Application/Sources/Scenes/Signup/SignupView.swift
Labels: chore

#11 ➰:: (#10) SDateUtil 추가
  Application/Project.swift
  Modules/SDateUtil/Project.swift
  Modules/SDateUtil/Sources/DateFormat.swift
  Modules/SDateUtil/Sources/DateToString.swift
  Modules/SDateUtil/Sources/SDateFormatter.swift
  Modules/SDateUtil/Sources/StringToDate.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Modules.swift
Labels: 기능 추가

#9 ➰:: (#1) AuthService
  Application/Project.swift
  Services/AuthService/Project.swift
  Services/AuthService/Sources/DI/AuthServiceDependency.swift
  Services/AuthService/Sources/Data/Local/DataSource/KeychainTypeForAuth.swift
  Services/AuthService/Sources/Data/Local/DataSource/LoaclTokenDataSource.swift
  Services/AuthService/Sources/Data/Local/DataSource/LoaclTokenDataSourceImpl.swift
  Services/AuthService/Sources/Data/Remote/API/AuthAPI.swift
  Services/AuthService/Sources/Data/Remote/Datasource/RemoteAuthDataSource.swift
  Services/AuthService/Sources/Data/Remote/Datasource/RemoteAuthDataSourceImpl.swift
  Services/AuthService/Sources/Data/Remote/Request/SigninRequest.swift
  Services/AuthService/Sources/Data/Remote/Response/SigninAndRefreshTokenResponse.swift
  Services/AuthService/Sources/Data/Repository/AuthRepositoryImpl.swift
  Services/AuthService/Sources/Domain/Entity/SigninEntity.swift
  Services/AuthService/Sources/Domain/Error/AuthServiceError.swift
  Services/AuthService/Sources/Domain/Repository/AuthRepository.swift
  Services/AuthService/Sources/Domain/UseCase/SigninUseCase.swift
  Services/AuthService/Sources/Plugin/JWTPulgin.swift
  Services/TestService/Sources/TempFile.swift
  Tuist/ProjectDescriptionHelpers/Project Frame/Project+Framework.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Services.swift
Labels: 기능 추가

#13 ➰:: (#12) GitHub action 추가
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/todo.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/CI.yml
  .github/workflows/SwiftLint.yml
  .swiftlint.yml
Labels: 프로젝트 설정

#15 ➰:: (#14) SNavigationAndTab 추가
  Application/Project.swift
  Modules/SNavigationAndTab/Project.swift
  Modules/SNavigationAndTab/Sources/BackToMainView.swift
  Modules/SNavigationAndTab/Sources/Entity/TabInformation.swift
  Modules/SNavigationAndTab/Sources/Environment/TabBarSelection.swift
  Modules/SNavigationAndTab/Sources/OnTabSelected.swift
  Modules/SNavigationAndTab/Sources/SNavigationAndTabContent.swift
  Modules/SNavigationAndTab/Sources/SNavigationAndTabView.swift
  Modules/SNavigationAndTab/Sources/Util/ViewToAnyView.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Modules.swift
Labels: 기능 추가

#17 ➰:: (#16) Router 추가
  Application/Sources/Application/ContentView.swift
  Application/Sources/Application/SunshijoApp.swift
  Application/Sources/Router/Route/Route/NavigationNode.swift
  Application/Sources/Router/Route/Route/Router.swift
  Application/Sources/Router/Route/Route/RouterFactory.swift
  Application/Sources/Router/Route/Route/Routing.swift
  Application/Sources/Router/Route/Route/View + Cover.swift
  Application/Sources/Router/Sunshijo/SunshijoRoute.swift
  Application/Sources/Router/Sunshijo/SunshijoRouter.swift
  Application/Sources/Router/Sunshijo/SunshijoeRouterFactory.swift
  Application/Sources/Scenes/ContentView.swift
Labels: 기능 추가

#19 ➰:: (#18) ResoucesCode
  Application/Resources/Colors.xcassets/Main 800.colorset/Contents.json
  Application/Resources/Colors.xcassets/Main 900.colorset/Contents.json
  Application/Resources/TempFile.swift
  Application/Sources/ResoucesCode/Color.swift
  Application/Sources/ResoucesCode/Image.swift
Labels: 기능 추가

#26 ➰:: (#25) auth binding
  Application/Resources/Colors.xcassets/AuthShadowColor.colorset/Contents.json
  Application/Resources/Colors.xcassets/Main 700.colorset/Contents.json
  Application/Sources/Application/SunshijoApp.swift
  Application/Sources/Components/Authcomponent/AuthButton.swift
  Application/Sources/Components/Authcomponent/AuthTextField.swift
  Application/Sources/Components/Authcomponent/GoToButton.swift
  Application/Sources/Components/Authcomponent/LoginButton.swift
  Application/Sources/ResoucesCode/Color.swift
  Application/Sources/Router/Sunshijo/SunshijoeRouterFactory.swift
  Application/Sources/Scenes/Login/LoginView.swift
  Application/Sources/Scenes/Login/LoginViewModel.swift
  Application/Sources/Scenes/Signup/SignupView.swift
  Application/Sources/Scenes/Signup/SignupViewModel.swift
  Application/Sources/extension/shadow.swift
  Services/AuthService/Sources/DI/AuthServiceDependency.swift
  Services/AuthService/Sources/Data/Remote/API/AuthAPI.swift
  Services/AuthService/Sources/Data/Remote/Datasource/RemoteAuthDataSource.swift
  Services/AuthService/Sources/Data/Remote/Datasource/RemoteAuthDataSourceImpl.swift
  Services/AuthService/Sources/Data/Remote/Request/SignupRequest.swift
  Services/AuthService/Sources/Data/Repository/AuthRepositoryImpl.swift
  Services/AuthService/Sources/Domain/Entity/SignupEntity.swift
  Services/AuthService/Sources/Domain/Repository/AuthRepository.swift
  Services/AuthService/Sources/Domain/UseCase/SignupUseCase.swift
Labels: 기능 추가, chore

#29 ➰ :: (#27) 수행평가페이지퍼블리싱
  Application/Resources/Images.xcassets/Etc.imageset/Contents.json
  Application/Resources/Images.xcassets/Etc.imageset/Vector.svg
  Application/Resources/Images.xcassets/Evaluation.imageset/Contents.json
  Application/Resources/Images.xcassets/Evaluation.imageset/archivebook.svg
  Application/Resources/Images.xcassets/Schedule.imageset/Contents.json
  Application/Resources/Images.xcassets/Schedule.imageset/calendar.svg
  Application/Resources/Images.xcassets/TimeTable.imageset/Contents.json
  Application/Resources/Images.xcassets/TimeTable.imageset/videotime.svg
  Application/Sources/Application/SunshijoApp.swift
  Application/Sources/Components/EvaluationComponent/CellElement.swift
  Application/Sources/Components/EvaluationComponent/EvaluationTitle.swift
  Application/Sources/ResoucesCode/Image.swift
  Application/Sources/ResourcesCode/Color.swift
  Application/Sources/ResourcesCode/Image.swift
  Application/Sources/Router/Sunshijo/SunshijoRoute.swift
  Application/Sources/Router/Sunshijo/SunshijoeRouterFactory.swift
  Application/Sources/Scenes/Etc/EtcView.swift
  Application/Sources/Scenes/Etc/EtcViewModel.swift
  Application/Sources/Scenes/Evaluation/EvaluationCell.swift
  Application/Sources/Scenes/Evaluation/EvaluationView.swift
  Application/Sources/Scenes/Evaluation/EvaluationViewModel.swift
  Application/Sources/Scenes/Login/LoginView.swift
  Application/Sources/Scenes/Main/MainView.swift
  Application/Sources/Scenes/Schedule/ScheduleView.swift
  Application/Sources/Scenes/Schedule/ScheduleViewModel.swift
  Application/Sources/Scenes/Signup/SignupView.swift
  Application/Sources/Scenes/TimeTable/TimeTableView.swift
  Application/Sources/Scenes/TimeTable/TimeTableViewModel.swift
  Application/Sources/extension/shadow.swift
  Services/AuthService/Sources/Data/Remote/API/AuthAPI.swift
Labels: 퍼블리싱

#31 ➰:: (#30) 코드 리펙토링
  Application/Resources/Colors.xcassets/AppIcon 1.appiconset/Contents.json
  Application/Resources/Colors.xcassets/Auth.colorset/Contents.json
  Application/Resources/Colors.xcassets/ShadowColor.colorset/Contents.json
  Application/Resources/Images.xcassets/Etc.imageset/Contents.json
  Application/Resources/Images.xcassets/Etc.imageset/Vector.svg
  Application/Resources/Images.xcassets/Etc.imageset/more.svg
  Application/Resources/Images.xcassets/Evaluation.imageset/Contents.json
  Application/Resources/Images.xcassets/Schedule.imageset/Contents.json
  Application/Resources/Images.xcassets/Sunshijo.imageset/Contents.json
  Application/Resources/Images.xcassets/TimeTable.imageset/Contents.json
  Application/Sources/Components/EvaluationComponent/CellElement.swift
  Application/Sources/ResourcesCode/Color.swift
  Application/Sources/Router/Sunshijo/SunshijoRoute.swift
  Application/Sources/Router/Sunshijo/SunshijoeRouterFactory.swift
  Application/Sources/Scenes/Etc/EtcView.swift
  Application/Sources/Scenes/Evaluation/Cell/EvaluationCell.swift
  Application/Sources/Scenes/Evaluation/EvaluationCell.swift
  Application/Sources/Scenes/Evaluation/EvaluationView.swift
  Application/Sources/Scenes/Schedule/ScheduleView.swift
  Application/Sources/Scenes/TimeTable/TimeTableView.swift
Labels: chore

#34 Feature/#33 component refactoring
  Application/Sources/Components/Authcomponent/AuthTextField.swift
  Application/Sources/Scenes/Login/LoginView.swift
  Application/Sources/Scenes/Signup/SignupView.swift
Labels: chore

#40 ➰:: (#38) RestApiModule 추가
  Application/Project.swift
  Modules/RestApiModule/Project.swift
  Modules/RestApiModule/Sources/RestApiRemoteDataSource.swift
  Modules/RestApiModule/Sources/SunshijoAPI.swift
  Services/AuthService/Sources/DI/AuthServiceDependency.swift
  Services/AuthService/Sources/Data/Local/DataSource/LoaclTokenDataSourceImpl.swift
  Services/AuthService/Sources/Domain/UseCase/CheckIsTokenValidUseCase.swift
  Services/AuthService/Sources/Domain/UseCase/FetchAccessTokenUseCase.swift
  Services/AuthService/Sources/Domain/UseCase/RefreshTokenIfExpiredUseCase.swift
  Services/AuthService/Sources/Domain/UseCase/RefreshTokenUseCase.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Modules.swift
Labels: 기능 추가, chore

#39 ➰ :: (#37) launch screen publishing
  Application/Sources/Application/SunshijoApp.swift
  Application/Sources/Router/Sunshijo/SunshijoRoute.swift
  Application/Sources/Router/Sunshijo/SunshijoeRouterFactory.swift
  Application/Sources/Scenes/LaunchScreen/LaunchScreenView.swift
Labels: 퍼블리싱, chore
