Repository Team-Sunshijo/Sunshijo-iOS, pull requests merged in 2023-06, with the labels that each got.

#42 ➰:: (#32) 시간표 퍼블리싱&TimeTableService 추가
  Application/Project.swift
  Application/Sources/Application/SunshijoApp.swift
  Application/Sources/Router/Sunshijo/SunshijoeRouterFactory.swift
  Application/Sources/Scenes/TimeTable/Cell/TimeTableCellView.swift
  Application/Sources/Scenes/TimeTable/TimeTableView.swift
  Application/Sources/Scenes/TimeTable/TimeTableViewModel.swift
  Services/AuthService/Sources/Data/Remote/DataSource/RemoteAuthDataSource.swift
  Services/AuthService/Sources/Data/Remote/DataSource/RemoteAuthDataSourceImpl.swift
  Services/TimeTableService/Project.swift
  Services/TimeTableService/Sources/DI/TimeTableServiceDependency.swift
  Services/TimeTableService/Sources/Data/Remote/API/TimeTableAPI.swift
  Services/TimeTableService/Sources/Data/Remote/DataSource/RemoteTimeTableDataSource.swift
  Services/TimeTableService/Sources/Data/Remote/DataSource/RemoteTimeTableDataSourceImpl.swift
  Services/TimeTableService/Sources/Data/Remote/Response/TimeTableListResponse.swift
  Services/TimeTableService/Sources/Data/Remote/Response/TimeTableResponse.swift
  Services/TimeTableService/Sources/Data/Repository/TimeTableRepositoryImpl.swift
  Services/TimeTableService/Sources/Domain/Entity/TimeTableEntity.swift
  Services/TimeTableService/Sources/Domain/Error/TimeTableServiceError.swift
  Services/TimeTableService/Sources/Domain/Repository/TimeTableRepository.swift
  Services/TimeTableService/Sources/Domain/UseCase/FetchTimeTableListUseCase.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/Services.swift
Labels: 퍼블리싱, 기능 추가

#45 ➰:: (#43) SunshijoDesign_iOS 추가
  Application/Project.swift
  Application/Resources/Colors.xcassets/AuthShadow.colorset/Contents.json
  Application/Resources/Colors.xcassets/AuthShadowColor.colorset/Contents.json
  Application/Resources/Colors.xcassets/Black.colorset/Contents.json
  Application/Resources/Colors.xcassets/Gray 100.colorset/Contents.json
  Application/Resources/Colors.xcassets/Gray 200.colorset/Contents.json
  Application/Resources/Colors.xcassets/Gray 300.colorset/Contents.json
  Application/Resources/Colors.xcassets/Gray 400.colorset/Contents.json
  Application/Resources/Colors.xcassets/Gray 50.colorset/Contents.json
  Application/Resources/Colors.xcassets/Gray 500.colorset/Contents.json
  Application/Resources/Colors.xcassets/Gray 600.colorset/Contents.json
  Application/Resources/Colors.xcassets/Gray 700.colorset/Contents.json
  Application/Resources/Colors.xcassets/Gray 800.colorset/Contents.json
  Application/Resources/Colors.xcassets/Gray 900.colorset/Contents.json
  Application/Resources/Colors.xcassets/Green 100.colorset/Contents.json
  Application/Resources/Colors.xcassets/Green.colorset/Contents.json
  Application/Resources/Colors.xcassets/Main 700.colorset/Contents.json
  Application/Resources/Colors.xcassets/Main 800.colorset/Contents.json
  Application/Resources/Colors.xcassets/Main 900.colorset/Contents.json
  Application/Resources/Colors.xcassets/Main.colorset/Contents.json
  Application/Resources/Colors.xcassets/Red 100.colorset/Contents.json
  Application/Resources/Colors.xcassets/Red.colorset/Contents.json
  Application/Resources/Colors.xcassets/Shadow.colorset/Contents.json
  Application/Resources/Colors.xcassets/Sub.colorset/Contents.json
  Application/Resources/Colors.xcassets/White.colorset/Contents.json
  Application/Sources/Components/Authcomponent/AuthButton.swift
  Application/Sources/Components/Authcomponent/AuthTextField.swift
  Application/Sources/Components/Authcomponent/GoToButton.swift
  Application/Sources/Components/EvaluationComponent/EvaluationTitle.swift
  Application/Sources/Extension/shadow.swift
  Application/Sources/ResourcesCode/Color.swift
  Application/Sources/Scenes/Etc/EtcView.swift
  Application/Sources/Scenes/Evaluation/Cell/EvaluationCell.swift
  Application/Sources/Scenes/Evaluation/EvaluationView.swift
  Application/Sources/Scenes/Login/LoginView.swift
  Application/Sources/Scenes/Schedule/ScheduleView.swift
  Application/Sources/Scenes/Signup/SignupView.swift
  Application/Sources/Scenes/TimeTable/Cell/TimeTableCellView.swift
  Application/Sources/Scenes/TimeTable/TimeTableView.swift
  Modules/SNavigationAndTab/Sources/SNavigationAndTabView.swift
  Tuist/Dependencies.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency/SPM.swift
Labels: 기능 추가, chore

#47 ➰ :: SunshijoDesign Version 1.0.3 -> 1.0.4
  Tuist/Dependencies.swift
Labels: 프로젝트 설정, chore

#49 ➰ :: #46 런치스크린 기능구현
  Application/Sources/Application/SunshijoApp.swift
  Application/Sources/Router/Sunshijo/SunshijoeRouterFactory.swift
  Application/Sources/Scenes/LaunchScreen/LaunchScreenView.swift
  Application/Sources/Scenes/LaunchScreen/LaunchScreenViewModel.swift
  Application/Sources/Scenes/Login/LoginView.swift
  Services/AuthService/Sources/Data/Remote/API/AuthAPI.swift
Labels: 기능 추가, chore

#53 ➰:: (#52) AppIcon 추가
  Application/Resources/Assets.xcassets/Color/AuthShadow.colorset/Contents.json
  Application/Resources/Assets.xcassets/Color/Contents.json
  Application/Resources/Assets.xcassets/Color/Shadow.colorset/Contents.json
  Application/Resources/Assets.xcassets/Contents.json
  Application/Resources/Assets.xcassets/Image/AppIcon.appiconset/Contents.json
  Application/Resources/Assets.xcassets/Image/AppIcon.appiconset/image 10.png
  Application/Resources/Assets.xcassets/Image/AppIcon.appiconset/image 11.png
  Application/Resources/Assets.xcassets/Image/AppIcon.appiconset/image 12.png
  Application/Resources/Assets.xcassets/Image/AppIcon.appiconset/image 13.png
  Application/Resources/Assets.xcassets/Image/AppIcon.appiconset/image 14.png
  Application/Resources/Assets.xcassets/Image/AppIcon.appiconset/image 15.png
  Application/Resources/Assets.xcassets/Image/AppIcon.appiconset/image 16.png
  Application/Resources/Assets.xcassets/Image/AppIcon.appiconset/image 17.png
  Application/Resources/Assets.xcassets/Image/AppIcon.appiconset/image 18.png
  Application/Resources/Assets.xcassets/Image/AppIcon.appiconset/image 19.png
  Application/Resources/Assets.xcassets/Image/AppIcon.appiconset/image 20.png
  Application/Resources/Assets.xcassets/Image/AppIcon.appiconset/image 21.png
  Application/Resources/Assets.xcassets/Image/AppIcon.appiconset/image 22.png
  Application/Resources/Assets.xcassets/Image/AppIcon.appiconset/image 23.png
  Application/Resources/Assets.xcassets/Image/AppIcon.appiconset/image 24.png
  Application/Resources/Assets.xcassets/Image/AppIcon.appiconset/image 9.png
  Application/Resources/Assets.xcassets/Image/Contents.json
  Application/Resources/Assets.xcassets/Image/Etc.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Etc.imageset/more.svg
  Application/Resources/Assets.xcassets/Image/Evaluation.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Evaluation.imageset/archivebook.svg
  Application/Resources/Assets.xcassets/Image/Schedule.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Schedule.imageset/calendar.svg
  Application/Resources/Assets.xcassets/Image/Sunshijo.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Sunshijo.imageset/image 8.svg
  Application/Resources/Assets.xcassets/Image/TimeTable.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/TimeTable.imageset/videotime.svg
  Application/Resources/Colors.xcassets/AppIcon.appiconset/Contents.json
Labels: 기능 추가

#51 ➰ :: #50 Edit Evaluation Screen
  Application/Sources/Scenes/Evaluation/Cell/EvaluationCell.swift
  Application/Sources/Scenes/Evaluation/EvaluationView.swift
  Tuist/Dependencies.swift
Labels: 퍼블리싱, 기능 추가, chore

#56 ➰:: (#55) etc publishing
  Application/Resources/Assets.xcassets/Image/BackButton.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/BackButton.imageset/arrowleft.svg
  Application/Resources/Assets.xcassets/Image/Logout.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/Logout.imageset/Frame 90296.svg
  Application/Resources/Assets.xcassets/Image/danger.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/danger.imageset/danger.svg
  Application/Resources/Assets.xcassets/Image/passwordcheck.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/passwordcheck.imageset/passwordcheck.svg
  Application/Resources/Assets.xcassets/Image/profile.imageset/Contents.json
  Application/Resources/Assets.xcassets/Image/profile.imageset/profile.svg
  Application/Sources/Modifier/Navigation/NavigationBackButtonWithRouter.swift
  Application/Sources/ResourcesCode/Image.swift
  Application/Sources/Router/Sunshijo/SunshijoRoute.swift
  Application/Sources/Router/Sunshijo/SunshijoeRouterFactory.swift
  Application/Sources/Scenes/EditPassword/EditPasswordView.swift
  Application/Sources/Scenes/EditPassword/EditPasswordViewModel.swift
  Application/Sources/Scenes/ErrorReport/ErrorReportView.swift
  Application/Sources/Scenes/ErrorReport/ErrorReportViewModel.swift
  Application/Sources/Scenes/Etc/EtcView.swift
  Application/Sources/Scenes/Etc/EtcViewModel.swift
  Application/Sources/Scenes/Etc/ServiceSectionView/ServiceListCellButtonView.swift
  Application/Sources/Scenes/Etc/ServiceSectionView/ServiceSectionButtonView.swift
  Application/Sources/Scenes/Main/MainView.swift
  Application/Sources/Scenes/Profile/ProfileView.swift
  Application/Sources/Scenes/Profile/ProfileViewModel.swift
  Services/AuthService/Sources/DI/AuthServiceDependency.swift
  Services/AuthService/Sources/Data/Local/DataSource/LocalTokenDataSource.swift
  Services/AuthService/Sources/Data/Local/DataSource/LocalTokenDataSourceImpl.swift
  Services/AuthService/Sources/Data/Repository/AuthRepositoryImpl.swift
  Services/AuthService/Sources/Domain/Repository/AuthRepository.swift
  Services/AuthService/Sources/Domain/UseCase/LogoutUseCase.swift
  Services/AuthService/Sources/Plugin/JWTPulgin.swift
  Tuist/Dependencies.swift
Labels: 퍼블리싱, 기능 추가
